### ISSUE TITLE
https://www.raspberrypi.org/learning/weather-station-guide/hardware-setup.md

### ISSUE THREAD

**Issue by DougieLawson** [raspberrypilearning/weather-station-guide#13]
There's a link to https://www.raspberrypi.org/learning/weather-station-guide/hardware-setup.md from https://www.raspberrypi.org/education/weather-station/faqs/ that's 404'd 

Can you fix that one?

Thanks, Dougie

**Comment by topshed** [comment]
Fixed, thanks.
