### ISSUE TITLE
Formatting issue in wind-vane.md

### ISSUE THREAD

**Issue by tyrower** [raspberrypilearning/weather-station-guide#2]
In the paragraph : **Analogue to digital conversion** : there appears to be a formatting issue due to an artefact from a former merge. [https://www.raspberrypi.org/learning/weather-station-guide/wind-vane.md](url)

Seems to be linked to the following Commit : [https://github.com/raspberrypilearning/weather-station-guide/commit/f397ba5322c57c1b6b4de6e0e8178db35c83e968](url)

Source  : [https://github.com/raspberrypilearning/weather-station-guide/blob/master/wind-vane.md](url) Lines 61 - 67

**Comment by LornaLynch** [comment]
That should be fixed now, but I think it will be a little while before the change shows on the website: I have it in mind that updates are pushed every hour? I'll close the issue for now, though, as it all looks fine in the GitHub text.

**Comment by tyrower** [comment]
Hi Lorna and co,

Thanks for the update. There is still however some double content even if
the formatting is now correct.

[image: Inline images 1]

Regards,
Alan

**Comment by LornaLynch** [comment]
Thanks Alan: I think it's definitely fixed now. Hopefully... 

Just FYI none of the images or links you sent came through for me: the links were 404ed and the image doesn't show. Not sure why!
