### ISSUE TITLE
Error in from email - register.md (new branch)

### ISSUE THREAD

**Issue by LornaLynch** [raspberrypilearning/weather-station-guide#6]
There's an error in the screenshot of the email sent to schools registering their Weather Stations (and presumably in the email itself): "...when you first login into the system" should read "...when you first log into the system". Could this be corrected in the email template and the screenshot?

**Comment by MarcScott** [comment]
I'll contact the database admin and get this fixed

**Comment by LornaLynch** [comment]
Thanks, @MarcScott!
